### ISSUE TITLE
Refactor ServerProxy into Admin and Game proxies

### ISSUE THREAD

**Issue by Jargonius** [joshuata/settlers-340#14]

**Comment by joshuata** [comment]
This is done already. All we need to do is remove the old server proxy class. Currently the proxy classes are mostly static. We might want to change that so that instances escalate. For example:

gap = new GameAdministrationProxy(connectionBroker)
UserOperationProxy uop = gap.login(username,password)
MoveProxy = uop.joinGame(game_id)

**Comment by joshuata** [comment]
Closed by 535efe2
